-- MySQL Script generated by MySQL Workbench
-- Fri Nov 12 19:22:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CondoTech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CondoTech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CondoTech` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `CondoTech` ;

-- -----------------------------------------------------
-- Table `CondoTech`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`pessoa` (
  `idPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` ENUM('ATIVO', 'BLOQUEADO', 'EXCLUIDO') NOT NULL DEFAULT 'BLOQUEADO',
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`condominio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`condominio` (
  `idCondominio` INT NOT NULL,
  `cnpj` VARCHAR(18) NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(14) NULL,
  `email` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `cep` VARCHAR(45) NULL,
  PRIMARY KEY (`idCondominio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`tipoOcorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`tipoOcorrencia` (
  `idTipoOcorrencia` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTipoOcorrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`ocorrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`ocorrencias` (
  `idOcorrencia` INT NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `idPessoa` INT NOT NULL,
  `idCondominio` INT NOT NULL,
  `idTipoOcorrencia` INT NOT NULL,
  PRIMARY KEY (`idOcorrencia`),
  INDEX `fk_ocorrencias_pessoa_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_ocorrencias_condominio1_idx` (`idCondominio` ASC) VISIBLE,
  INDEX `fk_ocorrencias_tipoOcorrencia1_idx` (`idTipoOcorrencia` ASC) VISIBLE,
  CONSTRAINT `fk_ocorrencias_pessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencias_condominio1`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencias_tipoOcorrencia1`
    FOREIGN KEY (`idTipoOcorrencia`)
    REFERENCES `CondoTech`.`tipoOcorrencia` (`idTipoOcorrencia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`avisos` (
  `idAviso` INT NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `data` DATETIME NOT NULL,
  `idPessoa` INT NOT NULL,
  `idCondominio` INT NOT NULL,
  PRIMARY KEY (`idAviso`, `idPessoa`, `idCondominio`),
  INDEX `fk_avisos_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_avisos_condominio1_idx` (`idCondominio` ASC) VISIBLE,
  CONSTRAINT `fk_avisos_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avisos_condominio1`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`areaComum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`areaComum` (
  `idAreaComum` INT NOT NULL AUTO_INCREMENT,
  `idCondominio` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`idAreaComum`),
  INDEX `fk_areaComum_condominio1_idx` (`idCondominio` ASC) VISIBLE,
  CONSTRAINT `fk_areaComum_condominio1`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`tarefaRecorrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`tarefaRecorrente` (
  `idTarefaRecorrente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `repeticaoDias` INT NULL,
  PRIMARY KEY (`idTarefaRecorrente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`ExecucaoTarefaRecorrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`ExecucaoTarefaRecorrente` (
  `idCondominio` INT NOT NULL,
  `idTarefaRecorrente` INT NOT NULL,
  `dataExecucao` DATETIME NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idCondominio`, `idTarefaRecorrente`),
  INDEX `fk_condominio_has_tarefaRecorrente_tarefaRecorrente1_idx` (`idTarefaRecorrente` ASC) VISIBLE,
  INDEX `fk_condominio_has_tarefaRecorrente_condominio1_idx` (`idCondominio` ASC) VISIBLE,
  INDEX `fk_ExecucaoTarefaRecorrente_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_condominio_has_tarefaRecorrente_condominio1`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_condominio_has_tarefaRecorrente_tarefaRecorrente1`
    FOREIGN KEY (`idTarefaRecorrente`)
    REFERENCES `CondoTech`.`tarefaRecorrente` (`idTarefaRecorrente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExecucaoTarefaRecorrente_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`DisponibilidadeArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`DisponibilidadeArea` (
  `idDisponibilidadeArea` INT NOT NULL AUTO_INCREMENT,
  `diaSemana` ENUM('SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', 'DOMINGO') NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFim` TIME NOT NULL,
  `vagas` INT NOT NULL DEFAULT 1,
  `idAreaComum` INT NOT NULL,
  INDEX `fk_DisponibilidadeArea_areaComum1_idx` (`idAreaComum` ASC) VISIBLE,
  PRIMARY KEY (`idDisponibilidadeArea`),
  CONSTRAINT `fk_DisponibilidadeArea_areaComum1`
    FOREIGN KEY (`idAreaComum`)
    REFERENCES `CondoTech`.`areaComum` (`idAreaComum`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`reserva` (
  `idPessoa` INT NOT NULL,
  `idAreaComum` INT NOT NULL,
  `idDisponibilidadeArea` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `vagasReservadas` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idPessoa`, `idAreaComum`),
  INDEX `fk_pessoa_has_areaComum_areaComum1_idx` (`idAreaComum` ASC) VISIBLE,
  INDEX `fk_pessoa_has_areaComum_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_Reserva_DisponibilidadeArea1_idx` (`idDisponibilidadeArea` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_areaComum_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_areaComum_areaComum1`
    FOREIGN KEY (`idAreaComum`)
    REFERENCES `CondoTech`.`areaComum` (`idAreaComum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_DisponibilidadeArea1`
    FOREIGN KEY (`idDisponibilidadeArea`)
    REFERENCES `CondoTech`.`DisponibilidadeArea` (`idDisponibilidadeArea`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`condomino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`condomino` (
  `idPessoa` INT NOT NULL,
  `idCondominio` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `idCondominio`),
  INDEX `fk_pessoa_has_condominio_condominio1_idx` (`idCondominio` ASC) VISIBLE,
  INDEX `fk_pessoa_has_condominio_pessoa1_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_condominio_pessoa1`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_has_condominio_condominio1`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CondoTech`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CondoTech`.`administradores` (
  `idPessoa` INT NOT NULL,
  `idCondominio` INT NOT NULL,
  `tipo` ENUM('SINDICO', 'VICE') NULL,
  PRIMARY KEY (`idPessoa`, `idCondominio`),
  INDEX `fk_pessoa_has_condominio_condominio2_idx` (`idCondominio` ASC) VISIBLE,
  INDEX `fk_pessoa_has_condominio_pessoa2_idx` (`idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_has_condominio_pessoa2`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `CondoTech`.`pessoa` (`idPessoa`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_pessoa_has_condominio_condominio2`
    FOREIGN KEY (`idCondominio`)
    REFERENCES `CondoTech`.`condominio` (`idCondominio`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
